name: Sync to Google Drive

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Rclone Config File
        run: |
          mkdir -p ~/.config/rclone
          cat << 'EOF' > ~/.config/rclone/rclone.conf
          [drive]
          type = drive
          scope = drive
          service_account_credentials = ${{ secrets.GDRIVE_CREDENTIALS }}
          EOF

      - name: Sync to Google Drive via Rclone
        uses: wei/rclone@v1
        with:
          args: sync . drive:${{ secrets.GDRIVE_FOLDER_ID }}
